<?php 
	$coupons = $this->getCoupons();
 ?>

<div class="grid">
	<div class="hor-scroll">
		<table cellspacing="0" class="data" id="customer_orders_grid_table">
            <thead>
                <tr class="headings">
                	<th><span class="nobr"><a href="#">Pedido #</a></span></th>
                	<th><span class="nobr"><a href="#" >Cupom</a></span></th>
                    <th><span class="nobr"><a href="#">Data da Compra</a></span></th>
                    <th class="no-link last"><span class="nobr"></span></th>
                </tr>                                 
       		</thead>     
        	<tbody>
        		<?php foreach ($coupons as $coupon): ?>
	            	<tr>            
		                <td><a href="<?php echo Mage::helper('adminhtml')->getUrl('adminhtml/sales_order/view', array('order_id'=>$coupon->getEntityId())); ?>"><?php echo $coupon->getIncrementId(); ?></a></td>
		                <td><?php echo $coupon->getCouponCode() ?>	</td>
		                <td><?php echo date('d/m/Y', Mage::getModel('core/date')->timestamp(strtotime($coupon->getCreatedAt()))); ?></td>
		                <td class="last">
		                    <a href="<?php echo Mage::helper('adminhtml')->getUrl('adminhtml/sales_order/view', array('order_id'=>$coupon->getEntityId())); ?>">Visualizar Pedido</a>
		              	</td>                                  
		            </tr>
		        <?php endforeach; ?>
    		</tbody>
    	</table>
    </div>
</div>
